#!/bin/bash

# Limpar variáveis de sessão
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Configurar ambiente XFCE
export XDG_CURRENT_DESKTOP="XFCE"
export XDG_MENU_PREFIX="xfce-"
export XDG_CONFIG_DIRS="/etc/xdg/xdg-xfce:/etc/xdg"

# Carregar recursos X
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# Configurar fundo
xsetroot -solid grey

# Iniciar XFCE
exec startxfce4