# .gitpod.yml
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-browser
  - port: 6080
    onOpen: open-browser

tasks:
  - init: |
      # Configurar Android SDK
      yes | sdkmanager --licenses
      sdkmanager "platform-tools" "platforms;android-33"